export const FUN_FACTS = [
  "Honey never spoils. Archaeologists have found pots of honey in ancient Egyptian tombs that are over 3,000 years old and still perfectly edible.",
  "Octopuses have three hearts. Two pump blood to the gills, while the third pumps it to the rest of the body.",
  "Bananas are berries, but strawberries are not. Botanically speaking, berries must develop from one flower with one ovary.",
  "A day on Venus is longer than a year on Venus. It takes Venus 243 Earth days to rotate once on its axis, but only 225 Earth days to orbit the Sun.",
  "Wombat poop is cube-shaped. This prevents it from rolling away and marks their territory effectively.",
  "There are more trees on Earth than stars in the Milky Way. Estimates suggest 3 trillion trees vs. 100-400 billion stars.",
  "Humans share 60% of their DNA with bananas.",
  "The Eiffel Tower can be 15 cm taller during the summer due to thermal expansion of the iron.",
  "A group of flamingos is called a 'flamboyance'.",
  "The shortest war in history lasted 38 minutes. It was between Britain and Zanzibar on August 27, 1896.",
  "Cleopatra lived closer in time to the Moon landing than to the construction of the Great Pyramid of Giza.",
  "Sloths can hold their breath longer than dolphins. They can slow their heart rate to one-third of its normal pace.",
  "The Unicorn is the national animal of Scotland.",
  "You can't hum while holding your nose closed.",
  "A cloud can weigh more than a million pounds.",
  "Nintendo was founded in 1889 as a playing card company.",
  "There is a species of jellyfish that is biologically immortal (Turritopsis dohrnii).",
  "Blue whales eat half a million calories in one mouthful.",
  "The total weight of ants on Earth once equaled the total weight of humans.",
  "Avocados are toxic to almost all animals except humans (and some sloths).",
];
