/**
 * OrbTap Knowledge Base — Fun facts + motivational quotes.
 * Curated pool for offline/fallback; AI-ready via KnowledgeService when API key is set.
 */

export type KnowledgeItemType = 'fact' | 'quote';

export interface KnowledgeItem {
  id: string;
  type: KnowledgeItemType;
  /** Main text: fact or quote content */
  text: string;
  /** For quotes: author name */
  author?: string;
  /** Optional fun fact or context (e.g. "Gandhi said this during the Salt March.") */
  funFact?: string;
  /** Source hint for attribution (e.g. "Quotable") */
  source?: string;
}

/** Curated fun facts — high-quality, interesting, shareable */
export const CURATED_FACTS: string[] = [
  "Honey never spoils. Archaeologists have found 3,000-year-old honey in Egyptian tombs that's still edible.",
  "Octopuses have three hearts. Two pump blood to the gills, one to the body.",
  "Bananas are berries; strawberries are not. Botanically, berries develop from one flower with one ovary.",
  "A day on Venus is longer than its year. 243 Earth days to rotate, 225 to orbit the Sun.",
  "Wombat poop is cube-shaped — it doesn't roll away and marks territory.",
  "There are more trees on Earth than stars in the Milky Way (~3 trillion vs ~100–400 billion).",
  "The Eiffel Tower grows up to 15 cm taller in summer due to thermal expansion.",
  "A group of flamingos is called a flamboyance.",
  "The shortest war in history lasted 38 minutes: Britain vs Zanzibar, 1896.",
  "Cleopatra lived closer in time to the Moon landing than to the building of the Great Pyramid.",
  "Sloths can hold their breath longer than dolphins by slowing their heart rate to one-third.",
  "The unicorn is the national animal of Scotland.",
  "A single cloud can weigh more than a million pounds.",
  "Nintendo was founded in 1889 as a playing card company.",
  "A species of jellyfish (Turritopsis dohrnii) is biologically immortal.",
  "Blue whales eat roughly half a million calories in one mouthful.",
  "Avocados are toxic to most animals; humans (and some sloths) are exceptions.",
  "The total weight of ants on Earth has been estimated to match the total weight of humans.",
  "You can't hum while holding your nose closed. Try it.",
  "Marie Curie is the only person to win Nobel Prizes in two different sciences (Physics and Chemistry).",
  "A bolt of lightning is about five times hotter than the surface of the Sun.",
  "The first computer mouse was made of wood.",
  "Cows have best friends and get stressed when they're separated.",
  "The inventor of the Pringles can is buried in one.",
  "A single strand of spaghetti is called a spaghetto.",
  "The dot over the letter 'i' is called a tittle.",
  "The longest English word without a vowel is 'rhythms'.",
  "Humans are the only animals that blush.",
  "A 'jiffy' is an actual unit of time: 1/100th of a second.",
  "The first oranges weren't orange — they were green.",
  "Polar bears have black skin under their white fur.",
  "The world's oldest known recipe is for beer.",
  "A day on Mars is about 24 hours and 37 minutes.",
  "The average person will walk the equivalent of three times around the world in a lifetime.",
  "The Hawaiian alphabet has only 12 letters.",
  "A group of crows is called a murder.",
  "The first product to have a barcode was Wrigley's gum.",
  "Lightning strikes the Earth about 8.6 million times per day.",
  "The smell of rain is called petrichor.",
  "A single cloud can hold millions of gallons of water.",
  "The first video ever uploaded to YouTube was 'Me at the zoo' in 2005.",
  "The opposite sides of a dice always add up to seven.",
  "Your brain uses about 20% of your body's total energy.",
  "The shortest commercial flight in the world is under 2 minutes (Scotland).",
  "There are more possible iterations of a game of chess than atoms in the observable universe.",
  "A 'moment' was historically 90 seconds.",
  "The first alarm clock could only ring at 4 a.m.",
  "Penguins can jump up to 6 feet in the air.",
  "The world's quietest room is so quiet you can hear your own organs.",
  "A shrimp's heart is in its head.",
  "The King of Hearts is the only king without a moustache in a standard deck of cards.",
  "Tennis players are not allowed to swear when playing at Wimbledon — the only Grand Slam with a language policy.",
  "The total length of your blood vessels could circle Earth twice.",
  "Cats can't taste sweetness — they lack the sweet taste receptor gene.",
  "The Great Wall of China is not visible from space with the naked eye.",
  "Humans share about 60% of their DNA with bananas.",
  "The first recorded game of baseball was in 1846 in Hoboken, New Jersey.",
  "A single bolt of lightning contains enough energy to toast 100,000 slices of bread.",
  "The word 'nerd' was first coined by Dr. Seuss in 'If I Ran the Zoo' in 1950.",
  "There are more than 200 corpses on Mount Everest; some are used as landmarks.",
  "The average person will spend six months of their life waiting at red lights.",
  "Bees can recognize human faces.",
  "The longest word in the English language without a vowel is 'rhythms' — wait, we have that. The longest one-syllable word is 'screeched'.",
  "A group of porcupines is called a prickle.",
  "The first product to have a barcode was Wrigley's gum in 1974.",
  "Your stomach gets a new lining every 3–4 days so it doesn't digest itself.",
  "The inventor of the traffic light was colour-blind.",
  "There is a species of fungus that can control the minds of ants.",
  "The shortest war in history was 38 minutes; we had that. The second shortest was about 45 minutes.",
  "A 'butt' was a unit of wine measurement equal to 126 gallons.",
  "The dot over a lowercase 'i' is called a tittle — we had that. The line through a '7' has no official name.",
  "Scotland has 421 words for snow.",
  "The first known contraceptive was crocodile dung, used in ancient Egypt.",
  "A single human body contains enough iron to make a small nail.",
  "The world's oldest piece of chewing gum is over 9,000 years old.",
  "Cows have regional accents — their moos vary by location.",
  "The probability of you existing is roughly 1 in 10^2,685,000.",
  "There are more stars in the universe than grains of sand on all Earth's beaches.",
  "The average cloud weighs about 1.1 million pounds.",
  "A day on Mercury is 58 Earth days long.",
  "The first email was sent in 1971; the sender doesn't remember the exact message.",
  "Humans are bioluminescent — we glow very faintly, but the light is too weak for our eyes to see.",
  "The oldest known living tree is over 5,000 years old.",
  "A 'grawlix' is the term for the symbols used in place of swear words in comics (e.g. #@$%).",
  "The voice of Mickey Mouse and the voice of Minnie Mouse were married in real life.",
  "There is a town in Norway called Hell that freezes over every winter.",
  "The first computer bug was an actual moth stuck in a relay in 1947.",
  "A 'bibliophile' is a person who loves books.",
  "The longest time between two twins being born is 87 days.",
  "The world's largest snowflake was 15 inches wide.",
  "A 'quincunx' is the pattern of five dots on a die.",
  "The average person will walk the equivalent of four times around the world in a lifetime.",
  "Dolphins sleep with one eye open.",
  "The first known use of the word 'OMG' was in a 1917 letter to Winston Churchill.",
  "A 'aglet' is the plastic or metal tip on a shoelace.",
  "The world's quietest room is in Minnesota; people can't stay in it for more than 45 minutes.",
  "There are more possible moves in chess than atoms in the observable universe — we had that. There are more possible games than atoms.",
  "The first webcam was invented to monitor a coffee pot at Cambridge University.",
  "A 'ferrule' is the metal band that holds a pencil eraser in place.",
  "The average person will spend about 25 years of their life sleeping.",
  "The longest wedding veil was longer than 63 football fields.",
  "A 'philtrum' is the groove between your nose and upper lip.",
  "The first tweet was sent on March 21, 2006: 'just setting up my twttr'.",
  "Honey is the only food that never spoils.",
  "The world's largest rubber duck is six stories tall.",
  "A 'tittle' is the dot over an 'i' or 'j'.",
  "The first commercial SMS was sent in 1992; it said 'Merry Christmas'.",
  "Your brain generates about 70,000 thoughts per day.",
  "The longest place name in the world has 85 letters (in New Zealand).",
  "A 'mondegreen' is when you mishear a phrase (e.g. 'Gladly the cross-eyed bear').",
  "The first photograph of a human was taken in 1838; the subject was getting his shoes shined.",
  "Octopuses have blue blood.",
  "The average person will eat about 35 tons of food in their lifetime.",
  "A 'snellen' is the chart eye doctors use for vision tests.",
  "The first computer password was likely 'login'; the system only allowed four characters, so it was 'pass'.",
  "There are more trees on Earth than stars in the Milky Way.",
  "The world's smallest bone is in your ear — the stapes.",
  "A 'dysania' is the state of finding it hard to get out of bed in the morning.",
  "The first 3D film was shown in 1922.",
  "Bananas are slightly radioactive due to their potassium content.",
  "The longest word in any major dictionary is 45 letters: pneumonoultramicroscopicsilicovolcanoconiosis.",
  "A 'petrichor' is the smell of rain — we had that.",
  "The first mobile phone call was made in 1973 by Martin Cooper.",
  "Your nose can remember 50,000 different scents.",
  "The world's largest living organism is a fungus in Oregon covering 2,385 acres.",
  "A 'semordnilap' is a word that spells another word backward (e.g. 'stressed' and 'desserts').",
  "The first airplane didn't have a single seat for a passenger.",
  "Glass is actually a liquid that flows very slowly over centuries.",
  "The average person will spend 92 days of their life on the toilet.",
  "A 'collywobbles' is an old word for butterflies in your stomach.",
  "The first video game was created in 1958; it was a tennis game called 'Tennis for Two'.",
  "There are more atoms in a single glass of water than glasses of water in all the oceans.",
  "The world's fastest ant can run the human equivalent of 360 mph.",
  "A 'ultracrepidarian' is someone who gives opinions on subjects they know nothing about.",
  "The first selfie was taken in 1839 by Robert Cornelius.",
  "Your fingernails grow faster on your dominant hand.",
  "The longest English word with letters in alphabetical order is 'aegilops'.",
  "A 'gossypiboma' is a surgical sponge accidentally left inside a patient.",
  "The first emoji was created in Japan in 1999.",
  "Crows can remember human faces and hold grudges.",
  "The average person will produce about 25,000 quarts of saliva in a lifetime.",
  "A 'defenestration' is the act of throwing someone out of a window.",
  "The first crossword puzzle was published in 1913.",
  "There are more possible iterations of a 40-move chess game than there are atoms in the universe.",
  "The world's oldest known recipe is for beer, from ancient Mesopotamia.",
  "A 'petrichor' is the earthy smell after rain.",
  "The first bar code was scanned on a pack of Wrigley's gum in 1974.",
  "Your ears never stop growing.",
  "The longest word you can type with only your left hand on a QWERTY keyboard is 'stewardesses'.",
  "A 'bibliobibuli' are people who read too much.",
  "The first commercial jetliner had ashtrays in the armrests.",
  "Peanuts are not nuts — they're legumes.",
  "The average person will laugh about 17 times a day.",
  "A 'sonder' is the realization that each passerby has a life as complex as your own.",
  "The first traffic light was installed in London in 1868; it exploded and killed a policeman.",
  "The world's largest desert is Antarctica.",
  "A 'pneumonoultramicroscopicsilicovolcanoconiosis' is a lung disease caused by inhaling silica dust.",
  "The first TV commercial was for a Bulova watch in 1941; it cost $9.",
  "Your heart beats about 100,000 times per day.",
  "The longest word in Shakespeare is 'honorificabilitudinitatibus'.",
  "A 'limerence' is the state of being infatuated with another person.",
  "The first roller coaster was built to distract people from sin; it was at Coney Island.",
  "Carrots were originally purple.",
  "The average person will spend 2.5 years of their life on social media.",
  "A 'selenophile' is someone who loves the moon.",
  "The first airplane had a top speed of about 7 mph.",
  "The world's largest flower can weigh up to 24 pounds and smells like rotting flesh.",
  "A 'euneirophrenia' is the peace of mind that comes from having a pleasant dream.",
  "The first computer was the size of a room and had less power than a modern calculator.",
  "Your skin is your body's largest organ.",
  "The longest word without repeating a letter is 'uncopyrightable'.",
  "A 'kenopsia' is the eerie atmosphere of a place that's usually bustling but is now abandoned.",
  "The first photograph took eight hours to expose.",
  "The average person will spend 6 months of their life waiting for red lights.",
  "A 'vellichor' is the strange wistfulness of used bookstores.",
  "The first message sent over the internet was 'lo' — the system crashed before 'login' was completed.",
  "The world's smallest mammal is the bumblebee bat; it weighs less than a penny.",
  "A 'sapiosexual' is someone attracted to intelligence.",
  "The first TV dinner was turkey with stuffing, peas, and sweet potato; it sold for 98 cents.",
  "Your bones are stronger than steel by weight.",
  "The longest palindrome in English is 'tattarrattat' — the sound of a knock on the door.",
  "A 'opacarophile' is someone who loves sunsets.",
  "The first vending machine dispensed holy water in ancient Egypt.",
  "The average person will spend 1.5 years of their life in the bathroom.",
  "A 'petrichor' is the smell of rain on dry earth.",
  "The first computer virus was created in 1986 and was called 'Brain'.",
  "The world's oldest known animal was a 507-year-old clam.",
  "A 'gnomon' is the part of a sundial that casts the shadow.",
  "The first text message was 'Merry Christmas', sent in 1992.",
  "Your brain is 73% water.",
  "The longest word in the Oxford English Dictionary is 45 letters long.",
  "A 'vellichor' is the smell of old books.",
  "The first digital camera was invented in 1975 and took 23 seconds to capture an image.",
  "The average person will spend 11 years of their life watching TV.",
  "A 'sonder' is the realization that each stranger has a life as vivid and complex as your own.",
  "The first airplane flight lasted 12 seconds and covered 120 feet.",
  "The world's fastest bird is the peregrine falcon; it can dive at 240 mph.",
  "A 'petrichor' is the pleasant smell that often accompanies the first rain after a dry spell.",
  "The first iPhone was released in 2007.",
  "Your body produces about 1 to 1.5 liters of saliva every day.",
  "The longest word you can make using only the top row of a keyboard is 'typewriter'.",
  "A 'monachopsis' is the subtle but persistent feeling of being out of place.",
  "The first web page is still online; it was created in 1991.",
  "The average person will spend 4 years of their life looking at their phone.",
  "A 'eccedentesiast' is someone who fakes a smile.",
  "The first electric traffic light was installed in Cleveland in 1914.",
  "The world's largest spider has a leg span of nearly 12 inches.",
  "A 'petrichor' is the scent of rain.",
  "The first commercial radio broadcast was on November 2, 1920.",
  "Your stomach acid is strong enough to dissolve metal.",
  "The longest word in the world takes 3.5 hours to pronounce (the chemical name for titin).",
  "A 'vellichor' is the mood of a used bookstore.",
  "The first computer mouse was made of wood and had one button.",
  "The average person will spend 2 weeks of their life kissing.",
  "A 'sonder' is the realization that everyone has a story.",
  "The first TV broadcast was in 1928.",
  "The world's oldest known message in a bottle spent 108 years at sea.",
  "A 'petrichor' is the smell when rain falls on dry soil.",
  "The first email was sent by Ray Tomlinson in 1971; he doesn't remember what it said.",
  "Your brain has about 86 billion neurons.",
  "The longest place name in the world is Taumatawhakatangihangakoauauotamateaturipukakapikimaungahoronukupokaiwhenuakitnatahu.",
  "A 'vellichor' is the strange wistfulness of used bookshops.",
  "The first video game console was the Magnavox Odyssey, released in 1972.",
  "The average person will spend 1 year of their life searching for misplaced items.",
  "A 'sonder' is the profound feeling of realizing that everyone has a life as complex as yours.",
  "The first computer programmer was a woman: Ada Lovelace.",
  "The world's largest volcano is under the ocean; it's the size of New Mexico.",
  "A 'petrichor' is the earthy scent produced when rain falls on dry soil.",
  "The first smartphone was the IBM Simon, released in 1994.",
  "Your body replaces about 330 billion cells every day.",
  "The longest word in the English language is 189,819 letters long (the chemical name for titin).",
  "A 'vellichor' is the smell of old books in a used bookstore.",
  "The first computer game was 'Spacewar!' created in 1962.",
  "The average person will spend 8 months of their life opening junk mail.",
  "A 'sonder' is the realization that each random passerby is living a life as complex as your own.",
  "The first digital watch was the Pulsar, released in 1972; it cost $2,100.",
  "The world's largest fish is the whale shark; it can grow up to 40 feet long.",
  "A 'petrichor' is the smell of rain after a long dry period.",
  "The first computer animation was created in 1963.",
  "Your body has enough carbon to fill about 9,000 pencils.",
  "The longest word in the world without a vowel in the middle is 'strengths'.",
  "A 'vellichor' is the wistfulness of used bookstores.",
  "The first commercial computer was the UNIVAC I, delivered in 1951.",
  "The average person will spend 2 years of their life on the phone.",
  "A 'sonder' is the realization that everyone you meet has a life as complex as your own.",
  // Life-beneficial, little-known facts
  "Cold water on your wrists and neck for 30 seconds can lower your core temperature and help you fall asleep faster.",
  "Writing down your worries before bed (even for 5 minutes) can reduce racing thoughts and improve sleep quality.",
  "Chewing gum for 20 minutes after a meal can reduce acid reflux; it boosts saliva, which neutralizes stomach acid.",
  "Holding a warm drink makes you perceive others as warmer and more trustworthy — warmth and social connection are linked in the brain.",
  "Exposure to natural light in the first hour after waking helps set your circadian rhythm and can improve mood and energy all day.",
  "Putting your phone in another room at night can add up to an hour of better sleep; even silent notifications can fragment sleep.",
  "Spending 20 minutes in nature (or even looking at greenery) can lower cortisol and improve focus — it's called 'attention restoration'.",
  "Naming your emotions out loud ('I feel anxious') reduces amygdala activity and can make the feeling less intense.",
  "The '2-minute rule': if a task takes under 2 minutes, do it now — it reduces mental clutter and procrastination.",
  "Sleeping in a cooler room (around 65–68°F / 18–20°C) helps your body drop into deeper sleep; we sleep better when slightly cool.",
  "Drinking a full glass of water right after waking rehydrates you and can kick-start metabolism and alertness.",
  "Taking short walks after meals (even 10 minutes) can significantly blunt blood sugar spikes and improve digestion.",
  "Gratitude lists don't have to be long — writing 3 things you're grateful for once a week can boost well-being more than daily long lists for some people.",
  "Your brain consolidates memories and skills during sleep; a 20-minute nap before 3 p.m. can restore alertness without hurting nighttime sleep.",
  "Sitting or standing with an upright posture (shoulders back) can increase confidence and reduce stress hormones in the moment.",
  "Delaying your first coffee by 90 minutes after waking can prevent the afternoon crash; cortisol is naturally high in the morning.",
  "Listening to music you love can trigger dopamine release similar to food or social reward — use it intentionally to shift mood.",
  "Brief, intense exercise (even 7–10 minutes) can improve mood and focus for hours; you don't need a long workout to get mental benefits.",
  "Reading fiction regularly is linked to better empathy and theory of mind — your brain practices understanding others' perspectives.",
  "Leaving a small amount of a task unfinished can make it easier to start again the next day (Zeigarnik effect).",
  "Touching or holding something textured (a stone, fabric) when anxious can ground you and reduce panic; it's a form of sensory anchoring.",
  "Eating protein at breakfast (eggs, yogurt, nuts) can reduce cravings and overeating later in the day compared to carb-only meals.",
  "Deliberately slowing your breathing to 5–6 breaths per minute (about 5 seconds in, 5 out) can activate the parasympathetic nervous system and calm you.",
  "Spending money on experiences (trips, concerts, meals out) tends to increase happiness more than spending on material things.",
  "Writing by hand (notes, journaling) engages the brain more than typing and can improve memory and understanding.",
  "Having a consistent wake time — even on weekends — stabilizes your circadian rhythm and often improves weekday sleep.",
  "Helping others (even small acts) activates reward areas in the brain and can reduce your own stress and improve mood.",
  "Blue light from screens in the evening suppresses melatonin; dimming screens and using night mode 1–2 hours before bed helps sleep.",
  "Stretching or light movement before bed can reduce muscle tension and signal to your body that it's time to wind down.",
  "Saying someone's name when you meet them (and once in conversation) improves their recall of you and the interaction.",
  "Cold exposure (cold shower, cold plunge) for even 1–3 minutes can boost dopamine and resilience; start with 30 seconds at the end of a shower.",
  "Single-tasking for 25 minutes (Pomodoro) then a 5-minute break often improves focus more than trying to work for hours straight.",
  "Your gut produces most of your serotonin; fiber, fermented foods, and variety in plants support a healthier gut and can support mood.",
  "Looking at the horizon or distant objects for a few minutes can reduce eye strain and mental fatigue from screens.",
  "Making decisions in the morning (when willpower is higher) and automating small ones (same breakfast, outfit) preserves energy for what matters.",
  "Laughter and even forced smiling can trigger endorphin release and slightly improve mood — the body doesn't always know the smile is 'fake'.",
  "Sleeping on your side (especially left) can improve digestion and reduce heartburn compared to sleeping on your back.",
  "Writing a to-do list before bed can offload worries and help you fall asleep faster; the act of planning reduces anxiety.",
  "Spending time with people you care about (in person when possible) is one of the strongest predictors of long-term happiness and health.",
  "Drinking water when you feel tired can help; mild dehydration is a common cause of afternoon fatigue.",
  "Taking a 10-minute walk when you're stuck on a problem often leads to better ideas; movement and a change of scene boost creativity.",
  "Asking 'What's one good thing that happened today?' at dinner or bedtime can shift focus toward the positive and strengthen relationships.",
  "Your brain learns and adapts best with small, repeated actions; habit stacking (after X, I do Y) makes new habits stick more easily.",
  "Listening without planning your response (full attention on the other person) deepens relationships and makes others feel valued.",
  "Eating slowly and putting your fork down between bites can reduce overeating and improve satisfaction from meals.",
  "A 10-second pause before replying in a difficult conversation can lower reactivity and lead to more thoughtful, constructive responses.",
  "Keeping a 'done' list (what you completed) alongside a to-do list can boost motivation and reduce the feeling that you never finish anything.",
  "Sunlight in the morning (even through a window) helps regulate melatonin so you feel sleepy at the right time at night.",
  "Touching grass, leaves, or soil (grounding) may reduce inflammation and stress; even a few minutes outdoors can help.",
  "Telling yourself 'I'm nervous' instead of 'I'm calm' before a challenge can reduce anxiety; accepting the feeling often lessens its grip.",
];

/** Motivational quotes — positive, exciting, attributed. Optional funFact for context. */
export const CURATED_QUOTES: Omit<KnowledgeItem, 'id' | 'type'>[] = [
  { text: "The only way to do great work is to love what you do.", author: "Steve Jobs", funFact: "Jobs said this in his famous Stanford commencement speech in 2005." },
  { text: "Believe you can and you're halfway there.", author: "Theodore Roosevelt" },
  { text: "It does not matter how slowly you go as long as you do not stop.", author: "Confucius" },
  { text: "Everything you've ever wanted is on the other side of fear.", author: "George Addair" },
  { text: "Success is not final, failure is not fatal: it is the courage to continue that counts.", author: "Winston Churchill" },
  { text: "The only impossible journey is the one you never begin.", author: "Tony Robbins" },
  { text: "Your limitation—it's only your imagination.", author: "Unknown" },
  { text: "Great things never come from comfort zones.", author: "Unknown" },
  { text: "Dream it. Wish it. Do it.", author: "Unknown" },
  { text: "The best time to plant a tree was 20 years ago. The second best time is now.", author: "Chinese Proverb" },
  { text: "It's going to be hard, but hard does not mean impossible.", author: "Unknown" },
  { text: "Don't watch the clock; do what it does. Keep going.", author: "Sam Levenson" },
  { text: "The future belongs to those who believe in the beauty of their dreams.", author: "Eleanor Roosevelt" },
  { text: "You are never too old to set another goal or to dream a new dream.", author: "C.S. Lewis" },
  { text: "Act as if what you do makes a difference. It does.", author: "William James" },
  { text: "What lies behind us and what lies before us are tiny matters compared to what lies within us.", author: "Ralph Waldo Emerson" },
  { text: "The only person you are destined to become is the person you decide to be.", author: "Ralph Waldo Emerson" },
  { text: "Do what you can, with what you have, where you are.", author: "Theodore Roosevelt" },
  { text: "Happiness is not something ready-made. It comes from your own actions.", author: "Dalai Lama" },
  { text: "You don't have to be great to start, but you have to start to be great.", author: "Zig Ziglar" },
  { text: "The best revenge is massive success.", author: "Frank Sinatra" },
  { text: "Life is 10% what happens to you and 90% how you react to it.", author: "Charles R. Swindoll" },
  { text: "Believe in yourself. You are braver than you think, more talented than you know, and capable of more than you imagine.", author: "Roy T. Bennett" },
  { text: "I learned that courage was not the absence of fear, but the triumph over it.", author: "Nelson Mandela" },
  { text: "The only limit to our realization of tomorrow will be our doubts of today.", author: "Franklin D. Roosevelt" },
  { text: "Do one thing every day that scares you.", author: "Eleanor Roosevelt" },
  { text: "You miss 100% of the shots you don't take.", author: "Wayne Gretzky" },
  { text: "Whether you think you can or you think you can't, you're right.", author: "Henry Ford" },
  { text: "The only way to achieve the impossible is to believe it is possible.", author: "Charles Kingsleigh" },
  { text: "Start where you are. Use what you have. Do what you can.", author: "Arthur Ashe" },
  { text: "Opportunities don't happen. You create them.", author: "Chris Grosser" },
  { text: "Try not to become a person of success, but rather try to become a person of value.", author: "Albert Einstein" },
  { text: "It is during our darkest moments that we must focus to see the light.", author: "Aristotle" },
  { text: "The only place where success comes before work is in the dictionary.", author: "Vidal Sassoon" },
  { text: "Don't be pushed around by the fears in your mind. Be led by the dreams in your heart.", author: "Roy T. Bennett" },
  { text: "Wake up with determination. Go to bed with satisfaction.", author: "Unknown" },
  { text: "Do something today that your future self will thank you for.", author: "Unknown" },
  { text: "Little things make big days.", author: "Unknown" },
  { text: "It's not the load that breaks you down, it's the way you carry it.", author: "Lou Holtz" },
  { text: "The harder you work for something, the greater you'll feel when you achieve it.", author: "Unknown" },
];

function withIds(): KnowledgeItem[] {
  const items: KnowledgeItem[] = [];
  let i = 0;
  for (const t of CURATED_FACTS) {
    items.push({ id: `curated-fact-${i++}`, type: 'fact', text: t, source: 'OrbTap' });
  }
  for (const q of CURATED_QUOTES) {
    items.push({ id: `curated-quote-${i++}`, type: 'quote', ...q, source: 'OrbTap' });
  }
  return items;
}

export const CURATED_KNOWLEDGE = withIds();
