/**
 * OrbTap legal documents — Terms of Service, Privacy Policy, Acceptable Use, Community Guidelines.
 * Written for App Store and Google Play compliance. Tailor with legal counsel for your jurisdiction.
 * For store approval: set EXPO_PUBLIC_LEGAL_ADDRESS in .env to a valid physical address (e.g. "123 Main St, City, State ZIP");
 * if unset, the app shows "See app store listing for address" — both stores prefer a real address in the listing or here.
 */

import { LEGAL_ADDRESS } from './AppLinks';

export const LEGAL_EFFECTIVE_DATE = 'January 1, 2025';

export interface LegalSection {
  title: string;
  body: string;
}

export const TERMS_OF_SERVICE: LegalSection[] = [
  { title: '1. ACCEPTANCE OF TERMS', body: 'By downloading, accessing, or using the OrbTap application or related services ("Services"), you agree to be bound by these Terms of Service ("Terms"). If you do not agree to these Terms, do not use the Services. OrbTap ("we," "us," or "our") reserves the right to modify these Terms at any time. Your continued use of the Services after changes are posted constitutes acceptance of the revised Terms. We will notify users of material changes via the app or email where appropriate.' },
  { title: '2. ELIGIBILITY', body: 'You must be at least 13 years of age (or the minimum age in your jurisdiction to consent to use of the Services) to use OrbTap. If you are under 18, you represent that you have your parent or guardian\'s permission. By using the Services, you represent that you have the legal capacity to enter into a binding agreement and that you are not prohibited from using the Services under applicable law.' },
  { title: '3. DESCRIPTION OF SERVICES', body: 'OrbTap provides a platform that enables users to discover and engage with partner locations, earn OT Points ("Points") through verified actions (e.g., visits, missions, redemptions), and redeem Points for perks, rewards, or other benefits offered by participating partners. The Services may include maps, partner listings, work-order scheduling, and social or community features. We do not guarantee availability of any specific partner, perk, or feature in any region.' },
  { title: '4. OT POINTS AND REWARDS', body: 'Points are in-app units that may be earned or spent within the Services. Points have no cash value, are not redeemable for cash, and are not a currency or security. We may adjust Point balances, earning rates, or redemption rules at any time. Points may expire or be forfeited upon account termination or for abuse. We are not liable for any loss of Points or perceived value. Partner offers and redemptions are subject to the partner\'s own terms and availability.' },
  { title: '5. ACCOUNT AND VERIFICATION', body: 'You must create an account and provide accurate information. You are responsible for maintaining the confidentiality of your account credentials. We may use location, device, or other signals to verify your presence or actions where relevant to earning or redeeming Points. Providing false information, spoofing location, or otherwise circumventing verification may result in immediate termination of your account and forfeiture of Points.' },
  { title: '6. ACCEPTABLE USE', body: 'You agree to use the Services only for lawful purposes and in accordance with our Acceptable Use Policy and Community Guidelines. You may not: (a) spoof or falsify location or identity; (b) abuse, harass, or harm other users or partners; (c) attempt to gain unauthorized access to our systems or other accounts; (d) use automation, bots, or scripts to earn Points or manipulate the Services; (e) resell or commercially exploit Points or rewards except as permitted; or (f) violate any applicable law. We may suspend or terminate your account for violations.' },
  { title: '7. INTELLECTUAL PROPERTY', body: 'All content, features, and functionality of the Services (including software, design, text, graphics, and logos) are owned by OrbTap or its licensors and are protected by copyright, trademark, and other laws. You may not copy, modify, distribute, or create derivative works without our express written permission. "OrbTap" and related marks are our trademarks.' },
  { title: '8. PRIVACY', body: 'Your use of the Services is also governed by our Privacy Policy. By using the Services, you consent to the collection, use, and disclosure of information as described in the Privacy Policy.' },
  { title: '9. DISCLAIMER OF WARRANTIES', body: 'THE SERVICES ARE PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT. WE DO NOT WARRANT THAT THE SERVICES WILL BE UNINTERRUPTED, ERROR-FREE, OR FREE OF HARMFUL COMPONENTS. YOUR USE OF THE SERVICES IS AT YOUR SOLE RISK.' },
  { title: '10. LIMITATION OF LIABILITY', body: 'TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, ORBTAP AND ITS AFFILIATES, OFFICERS, DIRECTORS, EMPLOYEES, AND AGENTS SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, OR ANY LOSS OF PROFITS, DATA, OR GOODWILL, ARISING OUT OF OR RELATED TO YOUR USE OF THE SERVICES, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. OUR TOTAL LIABILITY FOR ANY CLAIM ARISING OUT OF THESE TERMS OR THE SERVICES SHALL NOT EXCEED THE GREATER OF ONE HUNDRED U.S. DOLLARS ($100) OR THE AMOUNT YOU PAID TO US IN THE TWELVE (12) MONTHS PRECEDING THE CLAIM. SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OR LIMITATION OF CERTAIN DAMAGES; IN SUCH JURISDICTIONS, OUR LIABILITY SHALL BE LIMITED TO THE MAXIMUM EXTENT PERMITTED BY LAW.' },
  { title: '11. INDEMNIFICATION', body: 'You agree to indemnify, defend, and hold harmless OrbTap and its affiliates, officers, directors, employees, agents, and partners from and against any claims, damages, losses, liabilities, and expenses (including reasonable attorneys\' fees) arising out of or related to your use of the Services, your violation of these Terms, or your violation of any third-party rights.' },
  { title: '12. DISPUTE RESOLUTION AND ARBITRATION', body: 'Except where prohibited by law, any dispute arising out of or relating to these Terms or the Services shall be resolved by binding arbitration in accordance with the rules of the American Arbitration Association or similar body. You waive the right to a jury trial and to participate in a class action. Any arbitration shall be conducted on an individual basis. The prevailing party may be entitled to recover reasonable costs and fees. This section does not prevent either party from seeking injunctive relief in court for intellectual property or unauthorized use.' },
  { title: '13. TERMINATION', body: 'We may suspend or terminate your account and access to the Services at any time, with or without cause or notice, including for violation of these Terms or for operational or legal reasons. Upon termination, your right to use the Services and any Points or rewards may be forfeited. Provisions that by their nature should survive (including disclaimers, limitation of liability, indemnification, and dispute resolution) shall survive termination.' },
  { title: '14. GOVERNING LAW', body: 'These Terms shall be governed by the laws of the State of Delaware, United States, without regard to conflict of law principles. The United Nations Convention on Contracts for the International Sale of Goods does not apply.' },
  { title: '15. CONTACT', body: `For questions about these Terms, contact us at: legal@orbtap.com or OrbTap, Attn: Legal, ${LEGAL_ADDRESS}.` },
  { title: '16. APP STORE AND GOOGLE PLAY', body: 'If you access the Services through the Apple App Store or Google Play, you acknowledge that your use is also subject to the applicable store\'s terms of service and that this agreement is between you and OrbTap, not Apple or Google. Apple and Google have no obligation to provide maintenance or support. To the extent OrbTap offers in-app purchases or subscriptions (e.g., premium tier), payment will be charged to your Apple or Google account. Refunds are handled by Apple or Google in accordance with their respective policies. Any claims relating to the Services must be brought against OrbTap, not the store.' },
];

export const PRIVACY_POLICY: LegalSection[] = [
  { title: 'EFFECTIVE DATE', body: LEGAL_EFFECTIVE_DATE + '. We may update this Privacy Policy from time to time. We will notify you of material changes via the app or email.' },
  { title: '1. INTRODUCTION', body: 'OrbTap ("we," "us," or "our") respects your privacy. This Privacy Policy describes how we collect, use, disclose, and protect information when you use our mobile application and related services ("Services"). By using the Services, you consent to the practices described in this policy.' },
  { title: '2. INFORMATION WE COLLECT', body: 'We collect: (a) Account and profile information you provide (e.g., name, email, password, profile photo); (b) Location data when you enable location services, to verify visits, show nearby partners, and provide map features—we may collect precise or approximate location; (c) Device and usage information (device type, OS, app version, usage patterns, crash reports); (d) Transaction and activity data (Points earned or spent, redemptions, work orders, contest participation); (e) Communications you send to us (support, feedback); and (f) Information from partners or third parties where permitted (e.g., verification of a visit).' },
  { title: '3. HOW WE USE YOUR INFORMATION', body: 'We use the information to: provide, maintain, and improve the Services; verify your location or actions for Points and rewards; personalize content and offers; communicate with you (notifications, support, updates); detect and prevent fraud, abuse, and security incidents; comply with legal obligations; and for analytics and research to improve our Services. We may use aggregated or de-identified data for product and business purposes.' },
  { title: '4. SHARING OF INFORMATION', body: 'We do not sell your personal information. We may share information: (a) with participating partners to fulfill redemptions or verify visits, to the extent necessary; (b) with service providers who assist us (hosting, analytics, support), under contractual obligations to protect your data; (c) to comply with law, court order, or government request, or to protect rights, safety, or property; (d) in connection with a merger, sale, or transfer of assets; or (e) with your consent or at your direction.' },
  { title: '5. DATA RETENTION', body: 'We retain your information for as long as your account is active or as needed to provide the Services, comply with legal obligations, resolve disputes, and enforce our agreements. Location and usage data may be retained in aggregated or anonymized form. You may request deletion of your account and associated data subject to applicable law.' },
  { title: '6. SECURITY', body: 'We implement reasonable technical and organizational measures to protect your information against unauthorized access, alteration, disclosure, or destruction. No method of transmission or storage is 100% secure; we cannot guarantee absolute security.' },
  { title: '7. YOUR RIGHTS AND CHOICES', body: 'Depending on your jurisdiction, you may have the right to: access, correct, or delete your personal information; restrict or object to certain processing; data portability; or withdraw consent. You may update account details in the app or contact us. You may disable location services in your device settings, though some features may not work. To delete your account, use Settings or contact support. We will respond to requests in accordance with applicable law.' },
  { title: '8. CHILDREN', body: 'The Services are not directed to children under 13. We do not knowingly collect personal information from children under 13. If you believe we have collected such information, please contact us and we will take steps to delete it.' },
  { title: '9. INTERNATIONAL TRANSFERS', body: 'Your information may be processed in the United States or other countries where we or our service providers operate. By using the Services, you consent to the transfer of your information to countries that may have different data protection laws.' },
  { title: '10. THIRD-PARTY SERVICES', body: 'We use third-party services to operate the app, including Firebase (authentication, database, hosting, and cloud functions), Expo (app framework and tooling), and push notification providers. These providers may collect or process data on our behalf under contractual obligations to protect your information. We do not sell your personal information to third parties for their marketing. For App Store and Google Play transparency: data we collect may be "linked to you" (e.g., account, email, user ID) or "used for tracking" only where we have disclosed it (e.g., analytics to improve the app). We declare all data collection in the applicable store\'s privacy and data safety sections.' },
  { title: '11. PUSH NOTIFICATIONS', body: 'If you enable push notifications, we collect and use your device token to send you alerts (e.g., mission reminders, partner updates, or account notifications). You can disable push notifications in your device settings or in-app notification preferences at any time. Disabling may limit some features that rely on timely alerts.' },
  { title: '12. CONTACT', body: `For privacy-related questions or to exercise your rights, contact us at: privacy@orbtap.com or OrbTap, Attn: Privacy, ${LEGAL_ADDRESS}.` },
];

export const ACCEPTABLE_USE: LegalSection[] = [
  { title: 'EFFECTIVE DATE', body: LEGAL_EFFECTIVE_DATE + '.' },
  { title: '1. PURPOSE', body: 'This Acceptable Use Policy ("AUP") describes permitted and prohibited uses of the OrbTap application and services ("Services"). Violation may result in suspension or termination of your account and forfeiture of Points or rewards.' },
  { title: '2. PERMITTED USE', body: 'You may use the Services to discover partners, earn OT Points through legitimate verified actions (e.g., in-person visits, completing missions, redemptions), redeem Points for offered perks, participate in competitions and community features, and use work-order or other features as intended. You must provide accurate information and comply with all applicable terms and laws.' },
  { title: '3. PROHIBITED CONDUCT', body: 'You may not: (a) Spoof or falsify location, identity, or device information to earn Points or redeem rewards; (b) Use bots, scripts, automation, or other means to manipulate the Services or gain unfair advantage; (c) Abuse redemption or partner offers (e.g., resale, fraud, circumventing caps or cooldowns); (d) Harass, threaten, or harm other users, partners, or our staff; (e) Attempt to gain unauthorized access to our systems, other accounts, or partner systems; (f) Circumvent security, verification, or rate limits; (g) Use the Services for illegal purposes or to distribute malware; (h) Scrape or collect data from the Services without permission; or (i) Interfere with the integrity or availability of the Services.' },
  { title: '4. CONSEQUENCES', body: 'We may, without notice: remove or cancel Points; suspend or terminate your account; restrict access to features; or report conduct to law enforcement. We reserve the right to take any action we deem necessary to protect the Services and our users.' },
  { title: '5. REPORTING', body: 'If you become aware of a violation, report it via the in-app Report flow, Help Center, or support@orbtap.com. We will investigate and take appropriate action.' },
];

export const COMMUNITY_GUIDELINES: LegalSection[] = [
  { title: 'EFFECTIVE DATE', body: LEGAL_EFFECTIVE_DATE + '.' },
  { title: '1. BE RESPECTFUL', body: 'Treat other users, partners, and OrbTap staff with respect. No harassment, hate speech, bullying, or discrimination based on race, ethnicity, religion, gender, sexual orientation, disability, or other protected characteristics. Respectful disagreement is allowed; personal attacks are not.' },
  { title: '2. BE HONEST', body: 'Do not fake visits, spoof location, or otherwise misrepresent your actions to earn Points or rewards. Do not create fake accounts or misuse referral or invite features. Honest participation keeps the community and rewards system fair for everyone.' },
  { title: '3. SAFETY FIRST', body: 'Do not use the Services in a way that endangers yourself or others. Do not trespass on private property. Follow partner and venue rules when visiting locations. Do not share content that promotes violence or self-harm.' },
  { title: '4. PRIVACY AND CONSENT', body: 'Do not share others\' personal information without their consent. Do not impersonate others or use the Services to stalk or intimidate. Respect the privacy settings and choices of other users.' },
  { title: '5. CONTENT', body: 'User-generated content (e.g., in Spheres, feedback, or profiles) must not be illegal, harmful, or infringe others\' rights. We may remove content that violates these guidelines or our Terms. Repeated violations may result in account action.' },
  { title: '6. PARTNERS', body: 'Partners are independent; treat them fairly. Fraudulent redemptions or abuse of partner offers harm the entire community and may result in account termination and legal action.' },
  { title: '7. ENFORCEMENT', body: 'We may warn, restrict, or terminate accounts that violate these guidelines. Serious or repeated violations may result in permanent suspension. We reserve the right to update these guidelines and to take action as needed to keep the community safe and fair.' },
];
